import { INTENT_GROUPS, OBJECTIVES, SIMULATION_NOTICE, SOURCE_GAPS, VIEW_COPY } from './model.js'

export function buildMarkdown(brief, view = 'founder') {
  const copy = VIEW_COPY[view] || VIEW_COPY.founder
  const lines = [
    `# MCP Gateway Readiness Scanner - ${copy.reportTitle}`,
    '',
    SIMULATION_NOTICE,
    '',
    '## Gateway profile',
    '',
    `- Product: ${brief.profile.appName}`,
    `- Gateway source: ${brief.profile.provider}`,
    `- Gateway headline: ${brief.profile.currentModel}`,
    `- Tool surface: ${brief.profile.workload}`,
    `- Owner group: ${brief.profile.region}`,
    `- Tracked gateways: ${brief.profile.monthlyRequests || 'Not set'}`,
    `- Objective: ${objectiveLabel(brief.profile.objective)}`,
    `- Generated date: ${brief.generatedAt}`,
    '',
    '## Gateway summary',
    '',
    `- Overall readiness: ${brief.score.overall}/100`,
    `- Tool coverage: ${brief.score.impactCoverage}/100`,
    `- Owner clarity: ${brief.score.ownerClarity}/100`,
    `- Action clarity: ${brief.score.actionClarity}/100`,
    '',
    '## Gateway questions',
    '',
    ...brief.prompts.map((prompt) => `- ${prompt.prompt}`),
    '',
    '## Gateway issue matrix',
    '',
    '| Gateway item | Dependency | Owner | Risk | Status | Source gap | Recommended action |',
    '|---|---|---|---|---|---|---|',
    ...brief.findings.map((finding) => {
      const prompt = brief.prompts.find((item) => item.id === finding.promptId)
      return `| ${escapePipes(finding.prompt || prompt?.prompt || '')} | ${escapePipes(finding.dependency)} | ${escapePipes(finding.owner)} | ${escapePipes(finding.risk)} | ${finding.status} | ${SOURCE_GAPS[finding.likelySourceGap] || finding.likelySourceGap} | ${escapePipes(finding.recommendedAction)} |`
    }),
    '',
    '## Replay checklist',
    '',
    ...brief.readiness.map((check) => `- ${check.label}: ${check.state} - ${check.detail}`),
    '',
    '## Action checklist',
    '',
    ...brief.actions.map((action) => `- ${action.title} (impact ${action.impact}/5, effort ${action.effort}/5): ${action.why}`),
    '',
    '## Demo simulation disclaimer',
    '',
    SIMULATION_NOTICE,
    '',
    'Generated by MCP Gateway Readiness Scanner as a deterministic demo simulation. Validate with live gateway feeds and real telemetry before making production decisions.',
  ]

  return lines.join('\n')
}

export async function copyMarkdown(markdown, forceFallback = false) {
  if (forceFallback) {
    return { ok: false, reason: 'Fallback test requested.' }
  }

  try {
    if (!navigator.clipboard?.writeText) {
      throw new Error('Clipboard API unavailable')
    }
    await navigator.clipboard.writeText(markdown)
    return { ok: true }
  } catch (error) {
    return { ok: false, reason: error.message }
  }
}

export function downloadMarkdown(brief, markdown) {
  const fileName = `mcp-gateway-readiness-scanner-${slugify(brief.profile.appName) || 'app'}-brief.md`
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = fileName
  document.body.appendChild(link)
  link.click()
  link.remove()
  URL.revokeObjectURL(url)
  return fileName
}

function escapePipes(value) {
  return String(value || '').replaceAll('|', '\\|')
}

function slugify(value) {
  return String(value || '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
}

function objectiveLabel(id) {
  return OBJECTIVES.find((item) => item.id === id)?.label || id
}
