import { INTENT_GROUPS, SIMULATION_NOTICE, SOURCE_GAPS, VIEW_COPY } from './model.js'

export function buildMarkdown(brief, view = 'operator') {
  const copy = VIEW_COPY[view] || VIEW_COPY.operator
  const lines = [
    `# Workspace Agent Route Planner - ${copy.reportTitle}`,
    '',
    SIMULATION_NOTICE,
    '',
    '## Route profile',
    '',
    `- Workspace: ${brief.profile.appName}`,
    `- Signal source: ${brief.profile.provider}`,
    `- Route headline: ${brief.profile.currentModel}`,
    `- Workflow surface: ${brief.profile.workload}`,
    `- Owner group: ${brief.profile.region}`,
    `- Tracked workflows: ${brief.profile.monthlyRequests || 'Not set'}`,
    `- Objective: ${brief.profile.objective}`,
    `- Generated date: ${brief.generatedAt}`,
    '',
    '## Route summary',
    '',
    `- Overall readiness: ${brief.score.overall}/100`,
    `- Route coverage: ${brief.score.impactCoverage}/100`,
    `- Owner clarity: ${brief.score.ownerClarity}/100`,
    `- Access clarity: ${brief.score.actionClarity}/100`,
    '',
    '## Route questions',
    '',
    ...brief.prompts.map((prompt) => `- ${prompt.prompt}`),
    '',
    '## Workflow route matrix',
    '',
    '| Workflow | Dependency | Owner | Risk | Status | Signal gap | Recommended action |',
    '|---|---|---|---|---|---|---|',
    ...brief.findings.map((finding) => {
      const prompt = brief.prompts.find((item) => item.id === finding.promptId)
      return `| ${escapePipes(finding.prompt || prompt?.prompt || '')} | ${escapePipes(finding.dependency)} | ${escapePipes(finding.owner)} | ${escapePipes(finding.risk)} | ${finding.status} | ${SOURCE_GAPS[finding.likelySourceGap] || finding.likelySourceGap} | ${escapePipes(finding.recommendedAction)} |`
    }),
    '',
    '## Rollout checklist',
    '',
    ...brief.readiness.map((check) => `- ${check.label}: ${check.state} - ${check.detail}`),
    '',
    '## Action checklist',
    '',
    ...brief.actions.map((action) => `- ${action.title} (impact ${action.impact}/5, effort ${action.effort}/5): ${action.why}`),
    '',
    '## Demo simulation disclaimer',
    '',
    SIMULATION_NOTICE,
    '',
    'Generated by Workspace Agent Route Planner as a deterministic demo simulation. Validate with live agent discovery, real inventory data, and actual access controls before making production decisions.',
  ]

  return lines.join('\n')
}

export async function copyMarkdown(markdown, forceFallback = false) {
  if (forceFallback) {
    return { ok: false, reason: 'Fallback test requested.' }
  }

  try {
    if (!navigator.clipboard?.writeText) {
      throw new Error('Clipboard API unavailable')
    }
    await navigator.clipboard.writeText(markdown)
    return { ok: true }
  } catch (error) {
    return { ok: false, reason: error.message }
  }
}

export function downloadMarkdown(brief, markdown) {
  const fileName = `workspace-agent-route-planner-${slugify(brief.profile.appName) || 'app'}-brief.md`
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = fileName
  document.body.appendChild(link)
  link.click()
  link.remove()
  URL.revokeObjectURL(url)
  return fileName
}

function escapePipes(value) {
  return String(value || '').replaceAll('|', '\\|')
}

function slugify(value) {
  return String(value || '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
}
