import { INTENT_GROUPS, SIMULATION_NOTICE, SOURCE_GAPS, VIEW_COPY } from './model.js'

export function buildMarkdown(brief, view = 'founder') {
  const copy = VIEW_COPY[view] || VIEW_COPY.founder
  const lines = [
    `# ModelShift - ${copy.reportTitle}`,
    '',
    SIMULATION_NOTICE,
    '',
    '## Product / model profile',
    '',
    `- Product: ${brief.profile.appName}`,
    `- Primary provider: ${brief.profile.provider}`,
    `- Current model stack: ${brief.profile.currentModel}`,
    `- Fallback models: ${brief.profile.fallbackModels.length ? brief.profile.fallbackModels.map((item) => item.name).join(', ') : 'Not set'}`,
    `- Workload: ${brief.profile.workload}`,
    `- Region: ${brief.profile.region}`,
    `- Monthly requests: ${brief.profile.monthlyRequests || 'Not set'}`,
    `- Objective: ${brief.profile.objective}`,
    `- Generated date: ${brief.generatedAt}`,
    '',
    '## Migration readiness',
    '',
    `- Overall readiness: ${brief.score.overall}/100`,
    `- Provider independence: ${brief.score.providerIndependence}/100`,
    `- Fallback readiness: ${brief.score.fallbackReadiness}/100`,
    `- Regression coverage: ${brief.score.regressionCoverage}/100`,
    '',
    '## Top migration risks',
    '',
    ...brief.findings
      .filter((finding) => finding.status === 'risk' || finding.status === 'urgent')
      .slice(0, 5)
      .map((finding) => `- ${promptFor(brief, finding.promptId)} (${finding.status}): ${finding.recommendedAction}`),
    '',
    '## Fallback pressure',
    '',
    brief.summary.fallbackGap,
    '',
    '## Prompt findings',
    '',
    '| Migration question | Intent | Status | Migration gap | Recommended action |',
    '|---|---|---|---|---|',
    ...brief.findings.map((finding) => {
      const prompt = brief.prompts.find((item) => item.id === finding.promptId)
      return `| ${escapePipes(prompt?.prompt || '')} | ${INTENT_GROUPS[prompt?.intentGroup] || ''} | ${finding.status} | ${SOURCE_GAPS[finding.likelySourceGap] || finding.likelySourceGap} | ${escapePipes(finding.recommendedAction)} |`
    }),
    '',
    '## Readiness checklist',
    '',
    ...brief.readiness.map((check) => `- ${check.label}: ${check.state} - ${check.detail}`),
    '',
    "## This week's migration actions",
    '',
    ...brief.actions.map((action) => `- ${action.title} (impact ${action.impact}/5, effort ${action.effort}/5): ${action.why}`),
    '',
    '## Demo simulation disclaimer',
    '',
    SIMULATION_NOTICE,
    '',
    'Generated by ModelShift as a deterministic demo simulation. Validate with live model telemetry before making migration decisions.',
  ]

  return lines.join('\n')
}

export async function copyMarkdown(markdown, forceFallback = false) {
  if (forceFallback) {
    return { ok: false, reason: 'Fallback test requested.' }
  }

  try {
    if (!navigator.clipboard?.writeText) {
      throw new Error('Clipboard API unavailable')
    }
    await navigator.clipboard.writeText(markdown)
    return { ok: true }
  } catch (error) {
    return { ok: false, reason: error.message }
  }
}

export function downloadMarkdown(brief, markdown) {
  const fileName = `modelshift-${slugify(brief.profile.appName) || 'app'}-brief.md`
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = fileName
  document.body.appendChild(link)
  link.click()
  link.remove()
  URL.revokeObjectURL(url)
  return fileName
}

function promptFor(brief, promptId) {
  return brief.prompts.find((prompt) => prompt.id === promptId)?.prompt || promptId
}

function escapePipes(value) {
  return String(value || '').replaceAll('|', '\\|')
}

function slugify(value) {
  return String(value || '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
}
