import { INTENT_GROUPS, SIMULATION_NOTICE, SOURCE_GAPS, VIEW_COPY } from './model.js'

export function buildMarkdown(brief, view = 'founder') {
  const copy = VIEW_COPY[view] || VIEW_COPY.founder
  const lines = [
    `# AnswerRank - ${copy.reportTitle}`,
    '',
    SIMULATION_NOTICE,
    '',
    '## Brand / Category / Target buyer',
    '',
    `- Brand: ${brief.profile.brandName}`,
    `- Website: ${brief.profile.normalizedDomain}`,
    `- Category: ${brief.profile.category}`,
    `- Target buyer: ${brief.profile.targetBuyer || 'Not specified'}`,
    `- Objective: ${brief.profile.objective}`,
    `- Generated date: ${brief.generatedAt}`,
    '',
    '## Visibility score',
    '',
    `- Overall score: ${brief.score.overall}/100`,
    `- Citation readiness: ${brief.score.citationReadiness}/100`,
    `- Competitor pressure: ${brief.score.competitorPressure}/100`,
    '',
    '## Top missing buyer questions',
    '',
    ...brief.findings
      .filter((finding) => finding.status === 'missing' || finding.status === 'mispositioned')
      .slice(0, 5)
      .map((finding) => `- ${promptFor(brief, finding.promptId)} (${finding.status}): ${finding.recommendedAction}`),
    '',
    '## Competitor citation gaps',
    '',
    brief.summary.competitorGap,
    '',
    '## Prompt findings',
    '',
    '| Buyer question | Intent | Status | Source gap | Recommended action |',
    '|---|---|---|---|---|',
    ...brief.findings.map((finding) => {
      const prompt = brief.prompts.find((item) => item.id === finding.promptId)
      return `| ${escapePipes(prompt?.prompt || '')} | ${INTENT_GROUPS[prompt?.intentGroup] || ''} | ${finding.status} | ${SOURCE_GAPS[finding.likelySourceGap] || finding.likelySourceGap} | ${escapePipes(finding.recommendedAction)} |`
    }),
    '',
    '## Citation readiness',
    '',
    ...brief.readiness.map((check) => `- ${check.label}: ${check.state} - ${check.detail}`),
    '',
    "## This week's content fixes",
    '',
    ...brief.actions.map((action) => `- ${action.title} (impact ${action.impact}/5, effort ${action.effort}/5): ${action.why}`),
    '',
    '## Demo simulation disclaimer',
    '',
    SIMULATION_NOTICE,
    '',
    'Generated by AnswerRank as a deterministic demo simulation. Validate with live AI/search data before making business decisions.',
  ]

  return lines.join('\n')
}

export async function copyMarkdown(markdown, forceFallback = false) {
  if (forceFallback) {
    return { ok: false, reason: 'Fallback test requested.' }
  }

  try {
    if (!navigator.clipboard?.writeText) {
      throw new Error('Clipboard API unavailable')
    }
    await navigator.clipboard.writeText(markdown)
    return { ok: true }
  } catch (error) {
    return { ok: false, reason: error.message }
  }
}

export function downloadMarkdown(brief, markdown) {
  const fileName = `answerrank-${slugify(brief.profile.brandName) || 'brand'}-brief.md`
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = fileName
  document.body.appendChild(link)
  link.click()
  link.remove()
  URL.revokeObjectURL(url)
  return fileName
}

function promptFor(brief, promptId) {
  return brief.prompts.find((prompt) => prompt.id === promptId)?.prompt || promptId
}

function escapePipes(value) {
  return String(value).replaceAll('|', '\\|')
}

function slugify(value) {
  return String(value)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
}
