import { COST_DRIVERS, INTENT_GROUPS, SIMULATION_NOTICE, STATUS_LABELS, VIEW_COPY } from './model.js'

export function buildMarkdown(brief, view = 'founder') {
  const copy = VIEW_COPY[view] || VIEW_COPY.founder
  const lines = [
    `# CopilotBurn - ${copy.reportTitle}`,
    '',
    SIMULATION_NOTICE,
    '',
    '## Org profile',
    '',
    `- Organization: ${brief.profile.orgName}`,
    `- GitHub org: ${brief.profile.githubOrg}`,
    `- Plan: ${brief.profile.planLabel}`,
    `- Seats: ${brief.profile.seats}`,
    `- Active developers: ${brief.profile.activeDevelopers}`,
    `- Repos in scope: ${brief.profile.repos}`,
    `- PRs per month: ${brief.profile.prsPerMonth}`,
    `- Code review share: ${brief.profile.codeReviewShare}%`,
    `- Advanced model share: ${brief.profile.advancedModelShare}%`,
    `- Credit cap: ${brief.profile.monthlyCreditCap ? `${brief.profile.monthlyCreditCap} credits` : 'Not set'}`,
    `- Objective: ${brief.profile.objective}`,
    `- Generated date: ${brief.generatedAt}`,
    '',
    '## Spend forecast',
    '',
    `- Included credits: ${brief.forecast.includedCredits}`,
    `- Projected credits: ${brief.forecast.projectedCredits}`,
    `- Projected overage: ${brief.forecast.overageCredits}`,
    `- Buffer remaining: ${brief.forecast.bufferCredits}`,
    `- Usage ratio: ${brief.forecast.utilizationPercent}%`,
    `- Burn control score: ${brief.score.overall}/100`,
    '',
    '## Top cost drivers',
    '',
    brief.summary.costDriver,
    '',
    '## Prompt findings',
    '',
    '| Billing question | Intent | State | Cost driver | Recommended action |',
    '|---|---|---|---|---|',
    ...brief.findings.map((finding) => {
      const prompt = brief.prompts.find((item) => item.id === finding.promptId)
      return `| ${escapePipes(prompt?.prompt || '')} | ${INTENT_GROUPS[prompt?.intentGroup] || ''} | ${STATUS_LABELS[finding.status] || finding.status} | ${COST_DRIVERS[finding.likelySourceGap] || finding.likelySourceGap} | ${escapePipes(finding.recommendedAction)} |`
    }),
    '',
    '## Guardrails',
    '',
    ...brief.readiness.map((check) => `- ${check.label}: ${check.state} - ${check.detail}`),
    '',
    "## This week's cost controls",
    '',
    ...brief.actions.map((action) => `- ${action.title} (impact ${action.impact}/5, effort ${action.effort}/5): ${action.why}`),
    '',
    '## Demo simulation disclaimer',
    '',
    SIMULATION_NOTICE,
    '',
    'Generated by CopilotBurn as a deterministic demo simulation. Validate with live Copilot billing and usage data before making business decisions.',
  ]

  return lines.join('\n')
}

export async function copyMarkdown(markdown, forceFallback = false) {
  if (forceFallback) {
    return { ok: false, reason: 'Fallback test requested.' }
  }

  try {
    if (!navigator.clipboard?.writeText) {
      throw new Error('Clipboard API unavailable')
    }
    await navigator.clipboard.writeText(markdown)
    return { ok: true }
  } catch (error) {
    return { ok: false, reason: error.message }
  }
}

export function downloadMarkdown(brief, markdown) {
  const fileName = `copilotburn-${slugify(brief.profile.orgName) || 'org'}-brief.md`
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = fileName
  document.body.appendChild(link)
  link.click()
  link.remove()
  URL.revokeObjectURL(url)
  return fileName
}

function escapePipes(value) {
  return String(value).replaceAll('|', '\\|')
}

function slugify(value) {
  return String(value)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
}
